---
- name: configure user account + ssh keys
  hosts: all
  become: true

  tasks:
    - name: Create me
      ansible.builtin.user:
        name: judah
        state: present
        shell: /bin/bash
        create_home: true
        groups: sudo
        append: true
    - name: allow passwordless sudo
      ansible.builtin.copy:
        content: "judah ALL=(ALL) NOPASSWD:ALL\n"
        dest: /etc/sudoers.d/judah
        owner: root
        group: root
        mode: "0440"
    - name: add my ssh key
      ansible.posix.authorized_key:
        user: judah
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
